# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargs < Formula
  desc "Config file properties to cli arguments converter"
  homepage "https://github.com/Dafaque/cargs"
  version "1.0.3"
  license "TBA"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.3/cargs_1.0.3_darwin_amd64.tar.gz"
      sha256 "798ebab638476ef7c865764281d5636cfbab65b1b1d6c21a2ad8a2e458b1360a"

      def install
        bin.install "cargs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.3/cargs_1.0.3_darwin_arm64.tar.gz"
      sha256 "cbb8cdc1de5e1fa8cdc0ac9ecc2180b49e71f96da224e8c73c377d6cfc4b7833"

      def install
        bin.install "cargs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.3/cargs_1.0.3_linux_arm64.tar.gz"
      sha256 "b329c783d4c5d752ddf310cc40c653b5377a3371cff81a13b1595a9acbcd77c0"

      def install
        bin.install "cargs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.3/cargs_1.0.3_linux_amd64.tar.gz"
      sha256 "77e9a7e28b948c03c9c29705307a325c6ff8a611e3a095674d5a3965ee9a2870"

      def install
        bin.install "cargs"
      end
    end
  end

  def caveats
    <<~EOS
      cargs -h
    EOS
  end
end
