# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargs < Formula
  desc "Config file properties to cli arguments converter"
  homepage "https://github.com/Dafaque/cargs"
  version "1.0.1"
  license "TBA"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.1/cargs_1.0.1_darwin_amd64.tar.gz"
      sha256 "b3264b8a0cedca5e3679c122529c24d23c5f8ba9f43973e3bc81f0d4eaaeccbf"

      def install
        bin.install "cargs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.1/cargs_1.0.1_darwin_arm64.tar.gz"
      sha256 "de29e2b568f16ee4242e26c3d841dfeb46bf7b2a00a73b0a4d1d00927c3c4199"

      def install
        bin.install "cargs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.1/cargs_1.0.1_linux_arm64.tar.gz"
      sha256 "4c584e98e784802aa3e68371691dabddd326b7292ecfeb203d97fc8a7fdcf126"

      def install
        bin.install "cargs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/cargs/releases/download/v1.0.1/cargs_1.0.1_linux_amd64.tar.gz"
      sha256 "6981c734db5bcf975828414ec745ee63a9f18882d159b45a459620ab46a1a444"

      def install
        bin.install "cargs"
      end
    end
  end

  def caveats
    <<~EOS
      cargs -h
    EOS
  end
end
